use crate::models::*;
use bson::{oid::ObjectId, DateTime};

// Mock data for development and testing
pub struct MockData;

impl MockData {
    pub fn get_mock_champions() -> Vec<ChampionSummary> {
        vec![
            ChampionSummary {
                id: ObjectId::new(),
                name: "Ahri".to_string(),
                cost: 2,
                traits: vec!["Shapeshifter".to_string(), "Sorcerer".to_string()],
                health: 650.0,
                attack_damage: 40.0,
                ability_name: "Orb of Deception".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Ahri.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Akali".to_string(),
                cost: 3,
                traits: vec!["Ninja".to_string(), "Assassin".to_string()],
                health: 700.0,
                attack_damage: 65.0,
                ability_name: "Five Point Strike".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Akali.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Annie".to_string(),
                cost: 2,
                traits: vec!["Fortune".to_string(), "Sorcerer".to_string()],
                health: 550.0,
                attack_damage: 35.0,
                ability_name: "Disintegrate".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Annie.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Ashe".to_string(),
                cost: 3,
                traits: vec!["Frost".to_string(), "Ranger".to_string()],
                health: 600.0,
                attack_damage: 55.0,
                ability_name: "Frost Shot".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Ashe.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Caitlyn".to_string(),
                cost: 4,
                traits: vec!["Sniper".to_string(), "Ranger".to_string()],
                health: 550.0,
                attack_damage: 70.0,
                ability_name: "Piltover Peacemaker".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Caitlyn.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Darius".to_string(),
                cost: 1,
                traits: vec!["Warrior".to_string(), "Noxus".to_string()],
                health: 700.0,
                attack_damage: 50.0,
                ability_name: "Decimate".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Darius.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Jinx".to_string(),
                cost: 3,
                traits: vec!["Rogue".to_string(), "Gunner".to_string()],
                health: 550.0,
                attack_damage: 60.0,
                ability_name: "Switcheroo!".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Jinx.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Katarina".to_string(),
                cost: 3,
                traits: vec!["Assassin".to_string(), "Imperial".to_string()],
                health: 500.0,
                attack_damage: 55.0,
                ability_name: "Bouncing Blade".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Katarina.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Lux".to_string(),
                cost: 4,
                traits: vec!["Sorcerer".to_string(), "Demacia".to_string()],
                health: 600.0,
                attack_damage: 45.0,
                ability_name: "Light Binding".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Lux.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Miss Fortune".to_string(),
                cost: 1,
                traits: vec!["Gunner".to_string(), "Pirate".to_string()],
                health: 550.0,
                attack_damage: 45.0,
                ability_name: "Double Up".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/MissFortune.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Sett".to_string(),
                cost: 2,
                traits: vec!["Boss".to_string(), "Warrior".to_string()],
                health: 800.0,
                attack_damage: 55.0,
                ability_name: "Pit Grit".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Sett.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Vi".to_string(),
                cost: 3,
                traits: vec!["Enforcer".to_string(), "Piltover".to_string()],
                health: 750.0,
                attack_damage: 60.0,
                ability_name: "Vault Breaker".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Vi.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Yuumi".to_string(),
                cost: 3,
                traits: vec!["Cat".to_string(), "Mage".to_string()],
                health: 500.0,
                attack_damage: 45.0,
                ability_name: "Prowling Projectile".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Yuumi.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Zed".to_string(),
                cost: 2,
                traits: vec!["Ninja".to_string(), "Assassin".to_string()],
                health: 550.0,
                attack_damage: 55.0,
                ability_name: "Razor Shuriken".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Zed.png".to_string()),
            },
            ChampionSummary {
                id: ObjectId::new(),
                name: "Ziggs".to_string(),
                cost: 1,
                traits: vec!["Yordle".to_string(), "Artillery".to_string()],
                health: 450.0,
                attack_damage: 40.0,
                ability_name: "Bouncing Bomb".to_string(),
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/champion/Ziggs.png".to_string()),
            },
        ]
    }

    pub fn get_mock_items() -> Vec<ItemSummary> {
        vec![
            ItemSummary {
                id: ObjectId::new(),
                name: "Bloodthirster".to_string(),
                category: "AD".to_string(),
                item_type: "Completed".to_string(),
                description: "Grants lifesteal and attack damage".to_string(),
                is_unique: true,
                priority: 1,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3072.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Infinity Edge".to_string(),
                category: "AD".to_string(),
                item_type: "Completed".to_string(),
                description: "Increases critical strike damage".to_string(),
                is_unique: true,
                priority: 1,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3031.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Runaan's Hurricane".to_string(),
                category: "AD".to_string(),
                item_type: "Completed".to_string(),
                description: "Attacks hit additional nearby enemies".to_string(),
                is_unique: true,
                priority: 2,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3085.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Guinsoo's Rageblade".to_string(),
                category: "AD".to_string(),
                item_type: "Completed".to_string(),
                description: "Increases attack speed and ability power".to_string(),
                is_unique: true,
                priority: 1,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3124.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Rabadon's Deathcap".to_string(),
                category: "AP".to_string(),
                item_type: "Completed".to_string(),
                description: "Massively increases ability power".to_string(),
                is_unique: true,
                priority: 1,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3089.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Archangel's Staff".to_string(),
                category: "AP".to_string(),
                item_type: "Completed".to_string(),
                description: "Increases ability power and mana".to_string(),
                is_unique: true,
                priority: 1,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3003.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Jeweled Gauntlet".to_string(),
                category: "AP".to_string(),
                item_type: "Completed".to_string(),
                description: "Increases ability power and spell damage".to_string(),
                is_unique: true,
                priority: 1,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3136.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Warmog's Armor".to_string(),
                category: "Tank".to_string(),
                item_type: "Completed".to_string(),
                description: "Provides massive health and health regeneration".to_string(),
                is_unique: true,
                priority: 1,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3083.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Dragon's Claw".to_string(),
                category: "Tank".to_string(),
                item_type: "Completed".to_string(),
                description: "Provides magic resistance".to_string(),
                is_unique: true,
                priority: 2,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3116.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Bramble Vest".to_string(),
                category: "Tank".to_string(),
                item_type: "Completed".to_string(),
                description: "Reflects damage back to attackers".to_string(),
                is_unique: true,
                priority: 2,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3076.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Giant Slayer".to_string(),
                category: "AD".to_string(),
                item_type: "Completed".to_string(),
                description: "Deals bonus damage to high health enemies".to_string(),
                is_unique: true,
                priority: 1,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3036.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Statikk Shiv".to_string(),
                category: "AD".to_string(),
                item_type: "Completed".to_string(),
                description: "Attacks bounce to nearby enemies".to_string(),
                is_unique: true,
                priority: 2,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3087.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "B.F. Sword".to_string(),
                category: "AD".to_string(),
                item_type: "Component".to_string(),
                description: "Basic attack damage component".to_string(),
                is_unique: false,
                priority: 3,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1038.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Needlessly Large Rod".to_string(),
                category: "AP".to_string(),
                item_type: "Component".to_string(),
                description: "Basic ability power component".to_string(),
                is_unique: false,
                priority: 3,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1058.png".to_string()),
            },
            ItemSummary {
                id: ObjectId::new(),
                name: "Chain Vest".to_string(),
                category: "Tank".to_string(),
                item_type: "Component".to_string(),
                description: "Basic armor component".to_string(),
                is_unique: false,
                priority: 3,
                image_url: Some("https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1031.png".to_string()),
            },
        ]
    }

    pub fn get_mock_compositions() -> Vec<CompositionSummary> {
        vec![
            CompositionSummary {
                id: ObjectId::new(),
                name: "Ninja Assassin Carry".to_string(),
                category: "Assassin".to_string(),
                tier: "S".to_string(),
                difficulty: 3,
                winrate: 0.68,
                views: 15420,
                upvotes: 892,
                author: Some("TFTMaster".to_string()),
                champion_count: 8,
                main_champions: vec!["Akali".to_string(), "Zed".to_string(), "Katarina".to_string()],
                created_at: DateTime::now(),
            },
            CompositionSummary {
                id: ObjectId::new(),
                name: "Frost Ranger ADC".to_string(),
                category: "Ranger".to_string(),
                tier: "A".to_string(),
                difficulty: 2,
                winrate: 0.62,
                views: 12850,
                upvotes: 654,
                author: Some("IceQueen".to_string()),
                champion_count: 7,
                main_champions: vec!["Ashe".to_string(), "Caitlyn".to_string(), "Jinx".to_string()],
                created_at: DateTime::now(),
            },
            CompositionSummary {
                id: ObjectId::new(),
                name: "Sorcerer Burst Mage".to_string(),
                category: "Mage".to_string(),
                tier: "S".to_string(),
                difficulty: 4,
                winrate: 0.71,
                views: 18750,
                upvotes: 1243,
                author: Some("MagicMike".to_string()),
                champion_count: 9,
                main_champions: vec!["Ahri".to_string(), "Lux".to_string(), "Annie".to_string()],
                created_at: DateTime::now(),
            },
            CompositionSummary {
                id: ObjectId::new(),
                name: "Warrior Tank Frontline".to_string(),
                category: "Tank".to_string(),
                tier: "B".to_string(),
                difficulty: 2,
                winrate: 0.55,
                views: 8950,
                upvotes: 423,
                author: Some("TankMaster".to_string()),
                champion_count: 6,
                main_champions: vec!["Sett".to_string(), "Darius".to_string(), "Vi".to_string()],
                created_at: DateTime::now(),
            },
            CompositionSummary {
                id: ObjectId::new(),
                name: "Gunner Pirate ADC".to_string(),
                category: "Gunner".to_string(),
                tier: "A".to_string(),
                difficulty: 1,
                winrate: 0.59,
                views: 11200,
                upvotes: 567,
                author: Some("PirateKing".to_string()),
                champion_count: 7,
                main_champions: vec!["Miss Fortune".to_string(), "Jinx".to_string(), "Ziggs".to_string()],
                created_at: DateTime::now(),
            },
            CompositionSummary {
                id: ObjectId::new(),
                name: "Cat Mage Support".to_string(),
                category: "Mage".to_string(),
                tier: "B".to_string(),
                difficulty: 3,
                winrate: 0.52,
                views: 7650,
                upvotes: 298,
                author: Some("CatLover".to_string()),
                champion_count: 8,
                main_champions: vec!["Yuumi".to_string(), "Ahri".to_string(), "Lux".to_string()],
                created_at: DateTime::now(),
            },
        ]
    }
}